### PR TITLE
Added multipartFormRequest and refactored auth header

### PR DESCRIPTION
**Pull request by pj4533**
As you mentioned in my issue on AFNetworking (https://github.com/AFNetworking/AFNetworking/issues/815#issuecomment-13863968) the proper way to get a signed multipartFormRequest would be to override it, so I took a crack at doing so in AFOAuth1Client.

For tidy-ness I refactored the authorizationHeader stuff, since that function is only ever called from requestWithMethod, and I needed to do the same in multipartFormRequestWithMethod.

I tested by posting a photo to Tumblr and it seemed to work fine.

Let me know what you think!

### CODE REVIEW

**Comment by mattt** [comment]
Thanks so much for sharing this, @pj4533.

ed28a38424d4911f1fdcfa3cb26937117ed8482d wasn't the cleanest of merges, but I think everything got to where it needed to be. Let me know if anything looks amiss.

**Comment by iamcam** [comment]
@pj4533 I'm having trouble posting a photo to tumblr. Could you paste your code snipit? I can't tell if I"m doing something wrong, or if this bug hasn't been resolved in master - I can't get anything but a 401 using multipart. This is what I'm using:

(or @mattt maybe you know what's going on...)

```
    AFOAuth1Client *client = [[AFOAuth1Client alloc] initWithBaseURL:[NSURL URLWithString:kTumblrBaseAPI] key:kTumblrOAuthConsumerKey secret:kTumblrOauthConsumerSecret];
    [client setAccessToken:self.oauth_token];

    NSDictionary *parameters = @{
                                 @"type" : @"photo",
                                  @"caption" : @"This is a caption",
                                  @"data" : self.shareImageJpeg
                                  };

   NSMutableURLRequest *request = [client multipartFormRequestWithMethod:@"POST" path:@"blog/sdcameron.tumblr.com/post"  parameters:parameters constructingBodyWithBlock:^(id<AFMultipartFormData> formData) {
        [formData appendPartWithFileData:self.shareImageJpeg name:@"data" fileName:@"photo.jpg" mimeType:@"image/jpeg"];
    }];

    AFHTTPRequestOperation *operation = [[AFHTTPRequestOperation alloc] initWithRequest:request];

    [operation setCompletionBlockWithSuccess:^(AFHTTPRequestOperation *operation, id responseObject) {
        NSLog(@"Success!");
//        NSArray *responseJson = [NSJSONSerialization JSONObjectWithData:responseObject options:0 error:nil];
    } failure:^(AFHTTPRequestOperation *operation, NSError *error) {
        NSLog(@"Fail! %@", error.localizedDescription);

    }];
    [client enqueueHTTPRequestOperation:operation];
```

**Comment by pj4533** [comment]
Here is the function on my client, maybe cause you are using data as a param too?

``` objc
- (void) postPhotoWithData:(NSData *)photoData
                  withTags:(NSString *)tags
          withClickThruUrl:(NSString *)clickThruUrl
               withCaption:(NSString *)captionText
          intoBlogHostName:(NSString *)blogHostName
                   success:(void (^)(AFHTTPRequestOperation *operation, id responseObject))success
                   failure:(void (^)(AFHTTPRequestOperation *operation, NSError *error))failure;
{

    NSDictionary* params = @{
                             @"type" : @"photo",
                             @"tags" : tags,
                             @"caption" : captionText
                             };



    NSMutableURLRequest* request = [self multipartFormRequestWithMethod:@"POST"
                                                                   path:[NSString stringWithFormat:@"blog/%@/post", blogHostName]
                                                             parameters:params
                                              constructingBodyWithBlock:^(id<AFMultipartFormData> formData) {
                                                  [formData appendPartWithFileData:photoData name:@"data" fileName:@"photo.jpg" mimeType:@"image/jpg"];
                                              }];

    AFHTTPRequestOperation *operation = [self HTTPRequestOperationWithRequest:request success:success failure:failure];
    [self enqueueHTTPRequestOperation:operation];
}
```

I can dig in more later today, and I'll opensource my Tumblr AFOAuth1Client subclass too if that helps.

**Comment by iamcam** [comment]
This baffles me. I tried posting without `data` as a parameter last night and it was giving me the same problems. First thing this morning I boot up and retry with a successful post. So problem solved with a little bit of sleep, I guess :)

Thanks for the help and posting the code! At least I know I'm not totally losing it. Perhaps there was something else going on since I've always been able to make text posts and get user info this whole time.

**Comment by pj4533** [comment]
Well glad you figured it out.   I went ahead and created a repo & cocoapod for my AFTumblrAPIClient here https://github.com/pj4533/AFTumblrAPIClient

**Pull request merged**
