### PR TITLE
Fixed issue #54 and changed url for api 1.1

### PR DESCRIPTION
**Pull request by ignazioc**
Changed the method invocation for ios sample project (now include the scope parameter) and updated the url for twitter api 1.1

### CODE REVIEW

**Comment by prdlk** [comment]
How did you setup your application on the twitter website because when i change your keys to mine it gives me an error.

**Comment by ignazioc** [comment]
hum...nothing special i think. my app require readonly permission

**Comment by prdlk** [comment]
well i have read write, and dm do i need to do anything different

**Comment by prdlk** [comment]
I however also have a different issue in your appdelegate.h you have a openurl BOOL, but im placing the afoauth1 in a view controller. where would i put the openurl BOOL

**Comment by mattt** [comment]
Thanks so much for your patch, @ignazioc, but I just merged #50, which makes the same change. Also, your patch had a few unrelated changes (Xcode settings pointing source control to your fork, as well as colon-aligning whitespace) that would have been undesirable. Just something to consider when submitting PRs.

**Pull request closed without merging**
