### PR TITLE
Support for xAuth

### PR DESCRIPTION
**Pull request by hwaxxer**
A simple method to support xAuth. I didn't find any good general purpose xAuth libraries and think this would be a nice add-on to the best OAuth library.

### CODE REVIEW

**Comment by alexkarpenko** [comment]
This doesn't work for Twitter's xAuth since only x_auth_\* parameters should be sent in the HTTP POST body. Patch here: https://github.com/midnox/AFOAuth1Client/commit/9987bb6e019572037fd52994afdb492980060716

See Twitter's docs for details: https://dev.twitter.com/docs/oauth/xauth

**Comment by hwaxxer** [comment]
Thanks!

**Comment by alexkarpenko** [comment]
No problem! Now if only @mattt would hurry up and merge this :)

**Comment by jcouture** [comment]
I'm sure he will come around and merge this pull request soon enough. He speaks at MMConf (http://www.mmconf.com/), so he might have other things on his mind. :smile:

**Comment by alexkarpenko** [comment]
Oh, I'm sure he will. Between all the projects, conferences, and NSHipster, how does he even find time to sleep?! :smile:

**Comment by mattt** [comment]
Aww, you guys... :grin: 

It's been a while, but what is xAuth's relationship to OAuth, exactly? [AFXAuthClient](https://github.com/romaonthego/AFXAuthClient) is a thing. Is there anything this patch accomplishes that this library doesn't? Is this the right functionality to add to an OAuth library?

Just curious, is all.

**Comment by hwaxxer** [comment]
xAuth still needs OAuth signed requests which is why it leverages the functionality of AFOAuth1Client. But I do understand your concern. I could create a separate library, letting AFXAuthClient be a subclass of AFOAuth1Client. I think it'd be a nice edition to the AFNetworking suite as the xAuth paradigm seems to be growing in popularity (for better or worse).

**Pull request closed without merging**
