### PR TITLE
basically working, but still alpha

### PR DESCRIPTION
**Pull request by joergsimon**
So, this is a basically working version.

You can do authentication, you can set the token directly if you have the data, and you can sign the upcoming api requests.
I also changed the twitter client to have all calls.

Still I use that for a own project, so more tests will come, and the code is not the most beautiful currently. But it's a start. Will keep working on that

### CODE REVIEW

**Comment by mattt** [comment]
Looks pretty sweet—awesome work! 

I'm finally getting a chance to give this a real once-over, so I should be able to merge this in soon. The good news is that I see quite a bit of code we can delete :D

**Comment by mattt** [comment]
Update! I just pushed my merge branch to GitHub so you can watch its progress: https://github.com/mattt/AFOAuth1Client/tree/mattt-joergsimon-merge

My favorite part so far:

> 3 files changed, 168 insertions(+), 448 deletions(-)

**Comment by mattt** [comment]
...hopefully it all still works :p

**Comment by mattt** [comment]
Is there any way we could get this to use `CommonCrypto`, or some system library / framework that we wouldn't have to include in the project itself? Would you mind implementing that?

**Comment by joergsimon** [comment]
Currently I refactored the code a little bit to allow authentication using a UIWebView (thanks to a college of mine, georg, who initially set that up), and allowing data download by creating a Signed NSMutableUrlRequest for the HTTPOperation. But I will also look into that issue.

**Pull request merged**
