### PR TITLE
Rename kAFOAuthCredentialServiceName to kAFOAuth1CredentialServiceName

### PR DESCRIPTION
**Pull request by ejensen**
Fixes a duplicate symbol error when linking to AFOAuth2Client.

Ref https://github.com/AFNetworking/AFOAuth2Client/blob/master/AFOAuth2Client/AFOAuth2Client.m#L33

### CODE REVIEW

**Comment by mattt** [comment]
Thanks, @ejensen. Pushing a new release now.

**Comment by dcaunt** [comment]
Both constants still use the same value, AFOAuthCredentialService – wouldn't this cause problems if you use both clients and the same identifier?

Shouldn't both be renamed explicitly, i.e.

``` objective-c
kAFOAuth1CredentialServiceName = @"AFOAuth1CredentialService";
kAFOAuth2CredentialServiceName = @"AFOAuth2CredentialService";
```

**Comment by ejensen** [comment]
> Both constants still use the same value, AFOAuthCredentialService – wouldn't this cause problems if you use both clients and the same identifier?

@dcaunt Yes, keychain entries would be overridden when set with the identical identifier.

> Shouldn't both be renamed explicitly, i.e.
> 
> kAFOAuth1CredentialServiceName = @"AFOAuth1CredentialService";
> kAFOAuth2CredentialServiceName = @"AFOAuth2CredentialService";

I thought about renaming the service names as you suggested. But doing so, would cause all existing credentials stored under the previous service name  (`AFOAuthCredentialService`) to be inaccessible to the client. Upgrade would introduce a fairly significant change for those who haven't overridden the default service name.

@mattt Thoughts?

**Comment by mattt** [comment]
@ejensen It's an unfortunate conflation of constant values, but in practice, I think that the current setup is actually not a problem. After all, has anyone heard of a web service that provided authentication with OAuth 1 _and_ 2?

Regardless, these values could and probably should be renamed in a future minor or major release.

**Pull request merged**
