### PR TITLE
Unregister from application launch notifications

### PR DESCRIPTION
**Pull request by eriksundin**
I ran into problems when using the AFOAuth1Client in a process where there is log-out functionality in the application and the authentication process needs to be restarted.
The client never unregisters from the kAFApplicationLaunchedWithURLNotification notification, getting the result of multiple observation blocks getting executed.

Added functionality
- unregisters from the notification inside the notification block.
- handle the case where the user cancels an auth flow and returns to the app:
  -- unregister any previous registered notification block before registering a new one
  -- unregister in dealloc to fullfil the contract to addObserverForName:object:queue:usingBlock.

### CODE REVIEW

**Comment by yelled3** [comment]
looks great - I was just about to write it :-)
merge?

**Comment by seivan** [comment]
:+1: 
Nicely done.

**Comment by eriksundin** [comment]
Good points @seivan. The naming of the unregister method is not really clear, I used removeApplicationLaunchNotificationObserver instead to clearly reference the observer.

Also fixed the braces :-)

**Comment by mattt** [comment]
Merged! Thanks, @eriksundin! Tagging a new release now. Really happy to have this in for 0.2.0.

**Pull request merged**
